# -*- coding: utf-8 -*-
"""Test_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pzyZ7clquvynEMSgirFN2bR8disgVK5D
"""

# ssh -p 443 -R0:localhost:8000 a.pinggy.io

import requests

API_URL = "http://pjmvk-35-247-164-32.run.pinggy-free.link/translate"
def test_translation(text_to_translate):
    params = {"text": text_to_translate}
    try:
        response = requests.get(API_URL, params=params)
        if response.status_code == 200:
            data = response.json()
            print(f"Original: {data['original_text']}")
            print(f"Translated: {data['translated_text']}")
        else:
            print(f"Error: {response.status_code}")
    except Exception as e:
        print(f"An error occurred: {e}")

# Chạy thử
if __name__ == "__main__":
    print("--- Testing EnViT5 API ---")
    test_translation("en: Hello, how are you today?")
    test_translation("vi: Chúc bạn một ngày tốt lành!")

